name: flutter_ui_test
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get_it: ^7.2.0

  modal_bottom_sheet: ^2.0.1

  rxdart: ^0.27.7

  flutter_bloc: ^8.1.2

  equatable: ^2.0.5

  auto_size_text: ^3.0.0

  page_transition: ^2.0.9

  font_awesome_flutter: ^10.4.0

  flex_color_scheme: ^6.1.2

  go_router: ^6.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
